### ISSUE TITLE
auto reload

### ISSUE THREAD

**Issue by Nisthar** [appinteractive/electron-vite-tailwind-starter#44]
How to setup auto reload when background.js or other js files changes?

**Comment by appinteractive** [comment]
Hey @Nisthar I also struggled to get that working and only found ways that need a script file with a ton of configuration and third party packages. Did you found a solution for that in the meantime?

**Comment by Nisthar** [comment]
@appinteractive I haven't tried it yet but this package seems to do the job.
https://github.com/sindresorhus/electron-reloader/
Let me know if you get it working

**Comment by appinteractive** [comment]
@Nisthar thanks for that input, I did add it also to the template 👍
