### ISSUE TITLE
postcss.plugin was deprecated.

### ISSUE THREAD

**Issue by louwers** [appinteractive/electron-vite-tailwind-starter#85]
I get the following warning when I start the dev server:

```
postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```

**Comment by appinteractive** [comment]
Hey, sadly I was not able to get rid of that issue, the [fix](https://github.com/vitejs/vite/pull/873#issuecomment-730155021) that was in place does not work anymore.

[Here](https://github.com/vuejs/vue-next/issues/2642) you can see, that all are waiting for an upgrade to PostCSS 8 in @vue/compiler-sfc. 

But as far as I know, there is no issue with that, if so, you could use `tailwindcss@compat` if the message is anoying you.
