### ISSUE TITLE
VITE NOT READY

### ISSUE THREAD

**Issue by welcome14** [appinteractive/electron-vite-tailwind-starter#91]
Hi,
I have this 
"VITE NOT READY, WILL TRY AGAIN IN 200ms
READY
VITE NOT READY, WILL TRY AGAIN IN 200ms
VITE NOT READY, WILL TRY AGAIN IN 200ms
VITE NOT READY, WILL TRY AGAIN IN 200ms
VITE NOT READY, WILL TRY AGAIN IN 200ms" 

in my console and the desktop app reload continuos, why ?

**Comment by appinteractive** [comment]
Hey as the vite process may take a bit longer then the window creation I have added a retry as opening a window for an url that is not reachable will fail. 

Could it be, that there is an error in you app, which errors when opening it? It may have swollen the error message? Or is it rubbing on another port? 

Their might be a better way to deal with that retry issue but I'm not found it until now. But contributions are very welcome. 😎

**Comment by appinteractive** [comment]
@welcome14 did you found a Solution? Or was your vite running on another port?

**Comment by welcome14** [comment]
> @welcome14 did you found a Solution? Or was your vite running on another port? 

I have not tried.

**Comment by appinteractive** [comment]
Added a hint to the readme, thanks @joelbradbury!
